tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "direnv"
brew "nodenv"
brew "rbenv"
brew "java8"
brew "mas"
brew "ffmpeg"
brew "graphviz"
brew "jq"
brew "mitmproxy"
