HOME_BIN="$HOME/bin"
USR_LOCAL_BIN="/usr/local/bin"
USR_LOCAL_SBIN="/usr/local/sbin"
DOTFILES_BIN="$DOTFILES/bin"
NODENV="$HOME/.nodenv/bin"
HOME_LOCAL_BIN="$HOME/.local/bin"
BREW="/opt/homebrew/bin:/opt/homebrew/sbin"
export PATH="$BREW:$HOME_BIN:$USR_LOCAL_BIN:$USR_LOCAL_SBIN:$DOTFILES_BIN:$NODENV:$HOME_LOCAL_BIN:$PATH"
