HOME_BIN="$HOME/bin"
USR_LOCAL_BIN="/usr/local/bin"
USR_LOCAL_SBIN="/usr/local/sbin"
DOTFILES_BIN="$DOTFILES/bin"
HOME_LOCAL_BIN="$HOME/.local/bin"
MISE="$HOME/.local/share/mise/shims"
CARGO="$HOME/.cargo/bin"
export PATH="$MISE:$HOME_BIN:$USR_LOCAL_BIN:$USR_LOCAL_SBIN:$DOTFILES_BIN:$HOME_LOCAL_BIN:$CARGO:$PATH"